name: "Subscription API Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "Subscription API.postman_collection.json" -e "New Prod Subscription API UI.postman_environment.json" # also test 3 other envs
